Corrected version spec for galimatias in build.xml
build.xml listed version 0.0.2 but should have had 0.0.3. Attempting to run the "dist" target without this correction results in an error message like the following (on OSX 10.9.2 with JDK 1.7.0_25-b15):

	BUILD FAILED
	/Users/username/checker/build/build.xml:29: the archive galimatias-0.0.2.jar doesn't exist
	
	Total time: 1 second
	Error: Unable to access jarfile ./build/vnu/vnu.jar
	Traceback (most recent call last):
	  File "build/build.py", line 1106, in <module>
	    createDist()
	  File "build/build.py", line 688, in createDist
	    version = subprocess.check_output([javaCmd, "-jar", os.path.join(distDir, "vnu.jar"), "--version"]).rstrip()
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 575, in check_output
	    raise CalledProcessError(retcode, cmd, output=output)
	subprocess.CalledProcessError: Command '['java', '-jar', './build/vnu/vnu.jar', '--version']' returned non-zero exit status 1